var app = app || {};

app.NHOM_BAI_VIET = {
    HUONG_DAN: 1,
    QUAN_TRI_DU_AN: 2
};

app.LOAI_TAI_KHOAN = {
    TAI_KHOAN_CUC: 1,
    TAI_KHOAN_CHUYEN_GIA: 2,
    TAI_KHOAN_SO_Y_TE: 3
};

app.FORM_ID = {
    FORM_DANG_KY_HO_SO: 1
    , FORM_KE_TOAN_XAC_NHAN_THANH_TOAN: 11
    , FORM_MOT_CUA_RA_SOAT: 12
    , FORM_MOT_CUA_PHAN_CONG: 2
    , FORM_PHONG_BAN_PHAN_CONG: 21
    , FORM_THAM_XET_HO_SO: 3
    , FORM_PHO_PHONG_DUYET: 31
    , FORM_CHUYEN_GIA_THAM_DINH: 32
    , FORM_HOI_DONG_THAM_DINH: 33
    , FORM_TONG_HOP_THAM_XET_HO_SO: 34
    , FORM_TRUONG_PHONG_DUYET: 4
    , FORM_TRUONG_PHONG_DUYET_CONG_VAN: 41

    , FORM_LANH_DAO_CUC_DUYET: 5
    , FORM_LANH_DAO_CUC_DUYET_CONG_VAN: 51
    , FORM_LANH_DAO_BO_DUYET: 6
    , FORM_VAN_THU_DUYET: 7
    , FORM_VAN_THU_DUYET_CONG_VAN: 71

    , FORM_TRA_CUU_HO_SO: 9
    , FORM_THONG_KE_CHUNG: 91
    , FORM_THONG_KE_ADMIN: 92
    , FORM_THONG_KE_MOT_CUA: 93
    , FORM_THONG_KE_VAN_THU: 94
};

app.ROLE_LEVEL = {
    SA: 0,
    DOANH_NGHIEP: 1,
    KE_TOAN: 2,
    BO_PHAN_MOT_CUA: 3,
    VAN_THU: 4,
    LANH_DAO_BO: 5,
    LANH_DAO_CUC: 6,
    TRUONG_PHONG: 7,
    PHO_PHONG: 8,
    CHUYEN_VIEN: 9,
    CHUYEN_GIA: 10,
    TO_TRUONG_CHUYEN_GIA: 11,
    THANH_TRA: 101,
    DON_VI_TRUC_THUOC: 102
};

app.DON_VI_XU_LY = {
    DOANH_NGHIEP: 1
    , KE_TOAN: 2
    , MOT_CUA_TIEP_NHAN: 3
    , PHONG_BAN_PHAN_CONG: 4
    , TRUONG_PHONG: 5
    , LANH_DAO_CUC: 6
    , LANH_DAO_BO: 7
    , VAN_THU: 8
    , THANH_TRA: 9
    , CHUYEN_VIEN_THAM_XET: 10
    , CHUYEN_VIEN_PHOI_HOP_THAM_XET: 11
    , CHUYEN_VIEN_THAM_XET_TONG_HOP: 12
    , PHO_PHONG: 13
    , CHUYEN_GIA: 14
    , TO_TRUONG_CHUYEN_GIA: 15
    , HOI_DONG_THAM_DINH: 16
    , TRUONG_DOAN_THANH_TRA: 17
    , MOT_CUA_PHAN_CONG: 31
};

app.QUI_TRINH_THAM_DINH = {
    QT_1_CHUYEN_VIEN: 1,
    QT_2_CHUYEN_VIEN: 2
};

app.TRANG_THAI_DUYET_NHAP = {
    DUYET_NHAP: 1,
    DUYET_NHAP_SUA_DOI: 2,
    KHONG_DUYET: 0
};

app.TRANG_THAI_DUYET = {
    DUYET_DONG_Y: 1,
    DUYET_SUA_DOI: 2,
    KHONG_DUYET: 0
};

//TRANG THAI CONG VAN
app.TRANG_THAI_CONG_VAN = {
    KHONG_DAT: 0,
    DAT: 1,
    DAT_XIN_Y_KIEN: 2,
    CAN_BO_SUNG: 3,
    DAT_TRINH_LANH_DAO_KY: -1
};

//TrangThaiLienThongRequest
app.TRANG_THAI_LIEN_THONG_REQUEST = {
    HET_HAN_TOKEN: 1,
    KHONG_THANH_CONG: 2,
    THANH_CONG: 3,
    KHONG_CO_HO_SO_HOAC_DA_LIEN_THONG: 4
};

app.TEP_DINH_KEM = {
    GIAY_CONG_BO: 1,
    NOI_DUNG_QC: 2,
    MP4: 3,
    MP3: 4,
    KHAC: 5
};

app.LOAI_FILE = {
    MP4: 1,
    MP3: 2,
    PFD: 3
};

app.TRANG_THAI_HO_SO = {
    DA_LUU: 0,
    DA_NOP_HO_SO_MOI: 1,
    MOT_CUA_TRA_LAI: 11,
    CHO_DOANH_NGHIEP_THANH_TOAN: 12,
    CHO_KE_TOAN_XAC_NHAN: 13,
    THANH_TOAN_THAT_BAI: 14,
    CHO_TRA_GIAY_TIEP_NHAN: 19,
    MOT_CUA_DA_TIEP_NHAN: 2,
    SUA_DOI_BO_SUNG: 4,
    SUA_DOI_KHAC_PHUC: 41,
    DA_NOP_BO_SUNG: 5,
    DA_HOAN_TAT: 6,
    TU_CHOI_CAP_PHEP: 7,
    HO_SO_THAM_DINH_LAI: 8,
    CHO_PHEP_KHAO_NGHIEM: 99
};

app.LUONG_XU_LY_TT3 = {
    THAM_DINH_CHO_PHEP_KIEM_NGHIEM: 1,
    THAM_DINH_CAP_SO_DANG_KY: 2
};

app.TRANG_THAI_CONG_VAN_TT03 = {
    DUYET_KY_CHO_PHEP_KHAO_NGHIEM: 1,
    DUYET_KY_YEU_CAU_SUA_DOI_BO_SUNG: 2,
    DUYET_KY_KHONG_CHO_PHEP_KHAO_NGHIEM: 3,

    DUYET_CAP_SO_DANG_KY: 4,
    DUYET_YEU_CAU_SUA_DOI_BO_SUNG_CAP_SO_DANG_KY: 5,
    DUYET_KHONG_CAP_SO_DANG_KY: 6
};

app.TIEU_BAN_TT3 = {
    TIEU_BAN_DIET_CON_TRUNG: 1,
    TIEU_BAN_DIET_KHUAN: 2
};

app.LOAI_HO_SO = {
    TRONG_NUOC: 1,
    NUOC_NGOAI: 2
};
app.TT37_LOAI_TAI_LIEU_DINH_KEM = {
    VAN_BANG_CHUYEN_MON: 1,
    QUA_TRINH_THUC_HANH: 2,
    DU_DIEU_KIEN_SUC_KHOE: 3,
    LY_LICH_TU_PHAP: 4,
    ANH_4X6: 5,
    TAI_LIEU_KHAC: 6,
};
