// <auto-generated />
namespace newPSG.PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nam_update_13062020_22h23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nam_update_13062020_22h23));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131523565_nam_update_13062020_22h23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
