// <auto-generated />
namespace newPSG.PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nam_update_13062020_21h15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nam_update_13062020_21h15));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131416222_nam_update_13062020_21h15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
