// <auto-generated />
namespace newPSG.PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nam_up_1512020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nam_up_1512020));
        
        string IMigrationMetadata.Id
        {
            get { return "202011150845184_nam_up_1512020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
