//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace newPSG.PMS.vn.keypay.webservices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="kpWebservicesPortBinding", Namespace="http://kpWebservices/")]
    public partial class kpWebservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerryBillStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerryBillStatusV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmTransResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public kpWebservices() {
            this.Url = global::newPSG.PMS.Properties.Settings.Default.newPSG_PMS_Application_vn_keypay_webservices_kpWebservices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendOrderCompletedEventHandler sendOrderCompleted;
        
        /// <remarks/>
        public event QuerryBillStatusCompletedEventHandler QuerryBillStatusCompleted;
        
        /// <remarks/>
        public event QuerryBillStatusV2CompletedEventHandler QuerryBillStatusV2Completed;
        
        /// <remarks/>
        public event ConfirmTransResultCompletedEventHandler ConfirmTransResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kpWebservices/", ResponseNamespace="http://kpWebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendOrder(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string return_url, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string version, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string current_locale, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string currency_code, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string command, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_trans_id, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string country_code, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string good_code, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml_description, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string net_cost, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ship_fee, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tax, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_code, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string service_code, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secure_hash, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string desc_1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string desc_2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string desc_3, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string desc_4, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string desc_5, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customer_name, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customer_phone, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customer_address, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string customer_email, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string internal_bank) {
            object[] results = this.Invoke("sendOrder", new object[] {
                        return_url,
                        version,
                        current_locale,
                        currency_code,
                        command,
                        merchant_trans_id,
                        country_code,
                        good_code,
                        xml_description,
                        net_cost,
                        ship_fee,
                        tax,
                        merchant_code,
                        service_code,
                        secure_hash,
                        desc_1,
                        desc_2,
                        desc_3,
                        desc_4,
                        desc_5,
                        customer_name,
                        customer_phone,
                        customer_address,
                        customer_email,
                        internal_bank});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendOrderAsync(
                    string return_url, 
                    string version, 
                    string current_locale, 
                    string currency_code, 
                    string command, 
                    string merchant_trans_id, 
                    string country_code, 
                    string good_code, 
                    string xml_description, 
                    string net_cost, 
                    string ship_fee, 
                    string tax, 
                    string merchant_code, 
                    string service_code, 
                    string secure_hash, 
                    string desc_1, 
                    string desc_2, 
                    string desc_3, 
                    string desc_4, 
                    string desc_5, 
                    string customer_name, 
                    string customer_phone, 
                    string customer_address, 
                    string customer_email, 
                    string internal_bank) {
            this.sendOrderAsync(return_url, version, current_locale, currency_code, command, merchant_trans_id, country_code, good_code, xml_description, net_cost, ship_fee, tax, merchant_code, service_code, secure_hash, desc_1, desc_2, desc_3, desc_4, desc_5, customer_name, customer_phone, customer_address, customer_email, internal_bank, null);
        }
        
        /// <remarks/>
        public void sendOrderAsync(
                    string return_url, 
                    string version, 
                    string current_locale, 
                    string currency_code, 
                    string command, 
                    string merchant_trans_id, 
                    string country_code, 
                    string good_code, 
                    string xml_description, 
                    string net_cost, 
                    string ship_fee, 
                    string tax, 
                    string merchant_code, 
                    string service_code, 
                    string secure_hash, 
                    string desc_1, 
                    string desc_2, 
                    string desc_3, 
                    string desc_4, 
                    string desc_5, 
                    string customer_name, 
                    string customer_phone, 
                    string customer_address, 
                    string customer_email, 
                    string internal_bank, 
                    object userState) {
            if ((this.sendOrderOperationCompleted == null)) {
                this.sendOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendOrderOperationCompleted);
            }
            this.InvokeAsync("sendOrder", new object[] {
                        return_url,
                        version,
                        current_locale,
                        currency_code,
                        command,
                        merchant_trans_id,
                        country_code,
                        good_code,
                        xml_description,
                        net_cost,
                        ship_fee,
                        tax,
                        merchant_code,
                        service_code,
                        secure_hash,
                        desc_1,
                        desc_2,
                        desc_3,
                        desc_4,
                        desc_5,
                        customer_name,
                        customer_phone,
                        customer_address,
                        customer_email,
                        internal_bank}, this.sendOrderOperationCompleted, userState);
        }
        
        private void OnsendOrderOperationCompleted(object arg) {
            if ((this.sendOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendOrderCompleted(this, new sendOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kpWebservices/", ResponseNamespace="http://kpWebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuerryBillStatus([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string good_code, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string trans_id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secure_hash) {
            object[] results = this.Invoke("QuerryBillStatus", new object[] {
                        merchant_trans_id,
                        good_code,
                        trans_id,
                        merchant_code,
                        secure_hash});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QuerryBillStatusAsync(string merchant_trans_id, string good_code, string trans_id, string merchant_code, string secure_hash) {
            this.QuerryBillStatusAsync(merchant_trans_id, good_code, trans_id, merchant_code, secure_hash, null);
        }
        
        /// <remarks/>
        public void QuerryBillStatusAsync(string merchant_trans_id, string good_code, string trans_id, string merchant_code, string secure_hash, object userState) {
            if ((this.QuerryBillStatusOperationCompleted == null)) {
                this.QuerryBillStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerryBillStatusOperationCompleted);
            }
            this.InvokeAsync("QuerryBillStatus", new object[] {
                        merchant_trans_id,
                        good_code,
                        trans_id,
                        merchant_code,
                        secure_hash}, this.QuerryBillStatusOperationCompleted, userState);
        }
        
        private void OnQuerryBillStatusOperationCompleted(object arg) {
            if ((this.QuerryBillStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerryBillStatusCompleted(this, new QuerryBillStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kpWebservices/", ResponseNamespace="http://kpWebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuerryBillStatusV2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string good_code, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string trans_time, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secure_hash) {
            object[] results = this.Invoke("QuerryBillStatusV2", new object[] {
                        merchant_code,
                        merchant_trans_id,
                        good_code,
                        trans_time,
                        secure_hash});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QuerryBillStatusV2Async(string merchant_code, string merchant_trans_id, string good_code, string trans_time, string secure_hash) {
            this.QuerryBillStatusV2Async(merchant_code, merchant_trans_id, good_code, trans_time, secure_hash, null);
        }
        
        /// <remarks/>
        public void QuerryBillStatusV2Async(string merchant_code, string merchant_trans_id, string good_code, string trans_time, string secure_hash, object userState) {
            if ((this.QuerryBillStatusV2OperationCompleted == null)) {
                this.QuerryBillStatusV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerryBillStatusV2OperationCompleted);
            }
            this.InvokeAsync("QuerryBillStatusV2", new object[] {
                        merchant_code,
                        merchant_trans_id,
                        good_code,
                        trans_time,
                        secure_hash}, this.QuerryBillStatusV2OperationCompleted, userState);
        }
        
        private void OnQuerryBillStatusV2OperationCompleted(object arg) {
            if ((this.QuerryBillStatusV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerryBillStatusV2Completed(this, new QuerryBillStatusV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kpWebservices/", ResponseNamespace="http://kpWebservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConfirmTransResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_code, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string good_code, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string merchant_trans_id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string trans_id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string trans_result, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secure_hash) {
            object[] results = this.Invoke("ConfirmTransResult", new object[] {
                        merchant_code,
                        good_code,
                        merchant_trans_id,
                        trans_id,
                        trans_result,
                        secure_hash});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmTransResultAsync(string merchant_code, string good_code, string merchant_trans_id, string trans_id, string trans_result, string secure_hash) {
            this.ConfirmTransResultAsync(merchant_code, good_code, merchant_trans_id, trans_id, trans_result, secure_hash, null);
        }
        
        /// <remarks/>
        public void ConfirmTransResultAsync(string merchant_code, string good_code, string merchant_trans_id, string trans_id, string trans_result, string secure_hash, object userState) {
            if ((this.ConfirmTransResultOperationCompleted == null)) {
                this.ConfirmTransResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmTransResultOperationCompleted);
            }
            this.InvokeAsync("ConfirmTransResult", new object[] {
                        merchant_code,
                        good_code,
                        merchant_trans_id,
                        trans_id,
                        trans_result,
                        secure_hash}, this.ConfirmTransResultOperationCompleted, userState);
        }
        
        private void OnConfirmTransResultOperationCompleted(object arg) {
            if ((this.ConfirmTransResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmTransResultCompleted(this, new ConfirmTransResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void sendOrderCompletedEventHandler(object sender, sendOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QuerryBillStatusCompletedEventHandler(object sender, QuerryBillStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerryBillStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerryBillStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QuerryBillStatusV2CompletedEventHandler(object sender, QuerryBillStatusV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerryBillStatusV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerryBillStatusV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConfirmTransResultCompletedEventHandler(object sender, ConfirmTransResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmTransResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmTransResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591